<link rel="stylesheet" href="{{ asset('css/bootstrap.min.css') }}">
<link rel="stylesheet" href="{{ asset('css/animate.min.css') }}">
<link rel="stylesheet" href="{{ mix('css/min.magnific-popup.css') }}">
<link rel="stylesheet" href="{{ asset('css/fontawesome-all.min.css') }}">
<link rel="stylesheet" href="{{ mix('css/min.uicons-solid-rounded.css') }}">
<link rel="stylesheet" href="{{ asset('css/jquery.mCustomScrollbar.min.css') }}">
<link rel="stylesheet" href="{{ mix('css/min.flaticon.css') }}">
<link rel="stylesheet" href="{{ mix('css/min.slick.css') }}">
<link rel="stylesheet" href="{{ mix('css/min.default.css') }}">
<link rel="stylesheet" href="{{ mix('css/min.style.css') }}">
<link rel="stylesheet" href="{{ mix('css/min.responsive.css') }}">